---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::coreutils=9.4
  - conda-forge::grep=3.11
  - conda-forge::gzip=1.12
  - conda-forge::sed=4.9
  - conda-forge::tar=1.35